#!/usr/bin/python3
""" This Module contains a function hat returns a list
    of lists of integers representing the Pascal’s triangle
"""


def pascal_triangle(n):
    """  returns a list of lists of integers representing the Pascal’s triangle of n
        Args:
            n(int): size of the pascal triangle
    """
    if n <= 0:
        return []
    pascal_triangle = []
    for i in range(n):
        pascal_triangle.extend(i + 1)
        print()
    return pascal_triangle
